name: "Pull Request Docs Check"
on: 
  push:
    branches:
      - master
      - main


jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: linuxbuff/test3@master
      with:
        docs-folder: "docs/"

