name: linuxbuff-build-rtd-pages-and-pdf

# Loosely based on https://github.com/ammaraskar/sphinx-action-test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - dev
      - master


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-pages"
  update-pages:
    # The type of runner that the job will run on
    #runs-on: centos-latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2



      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx
          python -m pip install sphinx_rtd_theme
          python -m pip install sphinx-click
          python -m pip list




      - name: build docs
        run: |
          cd docs
          sphinx-build -b html -d ../../test3/doctrees   . ../../test3/html


      - name: build pdf
        run: |
          sudo apt-get update -y 
          sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra 
          cd docs
          make latexpdf
          
        
        

      - name: push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *
          git status
          git commit -m "Update" || true
          git push

         



